services:
  frontend:
    hostname: msm-frontend
    container_name: msm-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # The frontend needs to connect to the backend API
    environment:
      - API_URL=http://host.docker.internal:8000
