services:
  backend:
    build:
      context: ./fast_backend
      dockerfile: Dockerfile
    image: water-tariff-api
    hostname: water-tariff-backend
    container_name: water-tariff-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/watertariff
      - PORT=8000
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - proxy-network
  database:
    image: postgres:13
    restart: always
    hostname: database
    environment:
      POSTGRES_DB: watertariff
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - proxy-network
    volumes:
      - /Projects/innwater/water-tariff/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d watertariff" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  frontend:
    hostname: msm-frontend
    container_name: msm-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        base_href: /msm/
    restart: unless-stopped
    environment:
      - API_URL=http://water-tariff-backend:8000
      - base_href=/msm/
    depends_on:
      - backend
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge