from src.initial.schemas import LaunchModel, CoefficientModel, DemandModel, ConsumptionThresholds, TariffSectionModel, \
    SimulationPayload, WaterServiceCostModel, PrimitivesModel, EnvironmentalModel, TaxSectionModel, TaxModel, \
    SocialDataModel, PopulationModel, TariffModel

PAYLOAD = SimulationPayload(
    primitives=PrimitivesModel(
        ep=WaterServiceCostModel(
            couts_fixes=9000000,
            couts_variables=0.9,
            nombre_abonnes=47847,
        ),
        assainissement=WaterServiceCostModel(
            couts_fixes=6000000,
            couts_variables=0.40,
            nombre_abonnes=25300,
        ),
        environnement=EnvironmentalModel(
            couts_fixes_par_an=0,
            couts_variable_moyen=1.3,
        ),
        fiscalite=TaxSectionModel(
            eau_potable=TaxModel(
                tva=2.1,
                redevances=0.12,
            ),
            assainissement=TaxModel(
                tva=10,
                redevances=0.04,
            )
        ),
        donnees_sociales=SocialDataModel(
            seuil_par=3,
            seuil_car=3,
            pauvrete=800,
        )
    ),
    population=PopulationModel(
        bd="BD",
        eps=458,
        std=0.05,
    ),
    tarification=TariffModel(
        ep=TariffSectionModel(
            abonnement=18.69,
            usage_tiers=[
                ConsumptionThresholds(
                    seuil=0,
                    prix=0.878
                ),
                ConsumptionThresholds(
                    seuil=15,
                    prix=1.839
                ),
                ConsumptionThresholds(
                    seuil=30,
                    prix=2.768
                ),
                ConsumptionThresholds(
                    seuil=60,
                    prix=4.38
                ),
            ]
        ),
        assainissement=TariffSectionModel(
            abonnement=15.545,
            usage_tiers=[
                ConsumptionThresholds(
                    seuil=0,
                    prix=1.3,
                ),
                ConsumptionThresholds(
                    seuil=15,
                    prix=2.12,
                ),
                ConsumptionThresholds(
                    seuil=30,
                    prix=2.21,
                ),
                ConsumptionThresholds(
                    seuil=60,
                    prix=2.5,
                )
            ]
        )
    ),
    demande=DemandModel(
        coefficients=CoefficientModel(
            a0=-2.56,
            a1=0.48,
            a2=0.44,
            a3=0.12,
            a4=0.37,
            a5=-0.31,
            a6=0.25
        ),
        k=0.4,
        piscine=False,
        jardin=False
    ),
    launch=LaunchModel(
        periodes=4,
        nom_simulation="MockSimulation"
    )
)
